<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <TreatWarningsAsErrors>true</TreatWarningsAsErrors>
  </PropertyGroup>
  <ItemGroup>
    <FrameworkReference Include="Microsoft.AspNetCore.App" />
    <PackageReference Include="Relewise.Integrations.Umbraco" Version="17.0.0" />
    <PackageReference Include="Umbraco.Cms" Version="17.6.2" />
    <PackageReference Include="HtmlAgilityPack" Version="1.12.4" />
  </ItemGroup>
</Project>
