// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptionsViewObject = {
    readonly datasetId: string;
    readonly serverUrl?: string | null;
    readonly timeout: number;
};

export type ConfigurationViewModel = {
    trackedContentTypes: Array<string>;
    exportedContentTypes: Array<string>;
    named: Array<NamedOptionsViewObject>;
    contentMiddlewareEnabled: boolean;
};

export enum EventMessageTypeModel {
    DEFAULT = 'Default',
    INFO = 'Info',
    ERROR = 'Error',
    SUCCESS = 'Success',
    WARNING = 'Warning'
}

export type NamedOptionsViewObject = {
    name: string;
    tracker: ClientOptionsViewObject;
    recommender: ClientOptionsViewObject;
    searcher: ClientOptionsViewObject;
    searchAdministrator: ClientOptionsViewObject;
    analyzer: ClientOptionsViewObject;
    dataAccessor: ClientOptionsViewObject;
};

export type NotificationHeaderModel = {
    message: string;
    category: string;
    type: EventMessageTypeModel;
};

export type ConfigurationData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/umbraco/relewisedashboard/api/v1';
};

export type ConfigurationErrors = {
    /**
     * The resource is protected and requires an authentication token
     */
    401: unknown;
};

export type ConfigurationResponses = {
    /**
     * OK
     */
    200: ConfigurationViewModel;
};

export type ConfigurationResponse = ConfigurationResponses[keyof ConfigurationResponses];

export type ContentExportData = {
    body?: never;
    path?: never;
    query?: {
        permanentlyDelete?: boolean;
    };
    url: '/umbraco/relewisedashboard/api/v1';
};

export type ContentExportErrors = {
    /**
     * The resource is protected and requires an authentication token
     */
    401: unknown;
};

export type ContentExportResponses = {
    /**
     * OK
     */
    200: unknown;
};

export type ClientOptions = {
    baseUrl: 'https://localhost:44381' | (string & {});
};