// This file is auto-generated by @hey-api/openapi-ts

export enum EventMessageTypeModel {
    DEFAULT = 'Default',
    INFO = 'Info',
    ERROR = 'Error',
    SUCCESS = 'Success',
    WARNING = 'Warning'
}

export type NotificationHeaderModel = {
    message: string;
    category: string;
    type: EventMessageTypeModel;
};

export type ConfigurationData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/umbraco/relewisedashboard/api/v1';
};

export type ConfigurationErrors = {
    /**
     * The resource is protected and requires an authentication token
     */
    401: unknown;
};

export type ConfigurationResponses = {
    /**
     * OK
     */
    200: unknown;
};

export type ContentExportData = {
    body?: never;
    path?: never;
    query?: {
        permanentlyDelete?: boolean;
    };
    url: '/umbraco/relewisedashboard/api/v1';
};

export type ContentExportErrors = {
    /**
     * The resource is protected and requires an authentication token
     */
    401: unknown;
};

export type ContentExportResponses = {
    /**
     * OK
     */
    200: unknown;
};

export type ClientOptions = {
    baseUrl: 'https://localhost:44381' | (string & {});
};