name: backend

on: [pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: true
      matrix:
        dotnet-version: ["6.0.x", "7.0.x", "8.0.x"]
    steps:
      - uses: actions/checkout@v4

      - name: Setup .NET Core SDK ${{ matrix.dotnet-version }}
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: ${{ matrix.dotnet-version }}

      - name: Build with dotnet
        run: dotnet build src/Integrations.Umbraco/ --configuration Debug